[project]
name = "cs511project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "coremltools>=8.1",
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
    "ray>=2.39.0",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
]
